[project]
name = "musical-instrument-interface"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mido>=1.2.10",
    "numpy>=1.22",
    "python-rtmidi>=1.4.9",
    "sounddevice>=0.4.0",
]
